
spring.application.name=docservice
server.port=${PORT:8080}
management.endpoints.web.exposure.include=mappings,health
logging.level.org.springframework.web=INFO

# Multipart config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=-1
